from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal
import random
import string
from django.utils import timezone
from datetime import timedelta


def normalize_phone(raw):
    """Normalize phone numbers to digits-only E.164-like form."""
    if not raw:
        return ''
    digits = ''.join(ch for ch in str(raw) if ch.isdigit())
    if digits.startswith('0') and len(digits) == 10:
        digits = '233' + digits[1:]
    return digits


def generate_otp():
    return ''.join(random.choices(string.digits, k=6))


class OTPVerification(models.Model):
    """
    One-time password for email-verification (signup) and password-reset.

    SECURITY: only the SHA-256 hash of the code is stored on the row.
    Plaintext is generated by `create_for()`, sent to the user immediately,
    and then discarded. A DB read leak therefore can't yield active codes.

    Migrating from the older plaintext-`code` schema is handled by the
    accompanying migration which:
       - adds `code_hash` populated from sha256(code) for existing rows
       - keeps `code` for one release cycle as a fallback for any in-flight
         OTPs created before deploy (older rows still verify either way)
       - drops `code` in a follow-up migration once we're sure no plaintext
         OTPs are flying around
    """
    OTP_PURPOSE_CHOICES = [
        ('signup', 'Sign Up Verification'),
        ('password_reset', 'Password Reset'),
    ]
    user        = models.ForeignKey(User, on_delete=models.CASCADE, related_name='otps')
    code        = models.CharField(max_length=6, blank=True, default='',
                                   help_text='DEPRECATED: kept for backward-compat with pre-hash rows. New rows leave this empty.')
    code_hash   = models.CharField(max_length=64, blank=True, default='',
                                   db_index=True,
                                   help_text='SHA-256 of the 6-digit OTP. Authoritative.')
    purpose     = models.CharField(max_length=20, choices=OTP_PURPOSE_CHOICES, default='signup')
    is_used     = models.BooleanField(default=False)
    created_at  = models.DateTimeField(auto_now_add=True)

    def is_valid(self):
        """OTP is valid for 10 minutes."""
        return not self.is_used and timezone.now() < self.created_at + timedelta(minutes=10)

    def __str__(self):
        return f'OTP({self.purpose}) for {self.user.username}'

    @staticmethod
    def hash_code(code):
        """SHA-256 hex digest of a plaintext code. Used at create + verify time."""
        import hashlib as _h
        return _h.sha256(code.encode('utf-8')).hexdigest()

    def matches(self, entered_code):
        """
        Constant-time check that an entered OTP matches this row.
        Prefers code_hash; falls back to plaintext `code` for legacy rows
        created before the hash migration. New rows leave `code` empty so
        the fallback only fires for in-flight pre-deploy OTPs.
        """
        from django.utils.crypto import constant_time_compare
        entered = (entered_code or '').strip()
        if not entered:
            return False
        if self.code_hash:
            return constant_time_compare(self.hash_code(entered), self.code_hash)
        if self.code:
            # Legacy plaintext — accepted only until those rows expire (10 min).
            return constant_time_compare(self.code, entered)
        return False

    @classmethod
    def create_for(cls, user, purpose='signup'):
        """
        Generate a fresh OTP for `user`. Returns (otp_row, plaintext_code).
        Caller is expected to immediately deliver `plaintext_code` via
        send_otp() and then discard it — the row only stores the hash.
        """
        plaintext = generate_otp()
        row = cls.objects.create(
            user=user,
            purpose=purpose,
            code_hash=cls.hash_code(plaintext),
            # `code` left blank — never persist plaintext on new rows.
        )
        return row, plaintext


class UserProfile(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone           = models.CharField(max_length=20, blank=True)
    is_verified     = models.BooleanField(default=False)
    # Location — set on login/register via browser geolocation
    latitude        = models.FloatField(null=True, blank=True)
    longitude       = models.FloatField(null=True, blank=True)
    nearest_branch  = models.ForeignKey(
        'Branch', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='assigned_customers'
    )
    # Google OAuth (Sign in with Google)
    # google_id is the unique stable Google account ID; we use it as the
    # primary key for matching users instead of email so users can change
    # their Google email without losing their account.
    google_id       = models.CharField(max_length=64, blank=True, default='', db_index=True,
                                       help_text='Stable Google account ID — set when user signs in with Google.')
    email_verified  = models.BooleanField(default=False,
                                          help_text='True when the email address has been verified (via Google OAuth or OTP).')
    is_fulfillment_officer  = models.BooleanField(default=False,
                                          help_text='Marks this user as a branch fulfillment officer. They can log in to the fulfillment officer portal and process orders for the branch they manage.')
    can_upload_products     = models.BooleanField(default=False,
                                          help_text='Allow this fulfillment officer to add/upload products and images from the officer portal.')
    assigned_products       = models.ManyToManyField(
                                          'Product', blank=True, related_name='assigned_officers',
                                          help_text='Products this fulfillment officer is responsible for processing/handling.')

    def __str__(self):
        return f'Profile({self.user.username})'


class PaymentSettings(models.Model):
    """
    Payment gateway configuration. Each row represents one configured
    can have multiple rows but typically only one or two will have
    `is_active=True`. The checkout view picks the first active row at
    request time.

    To support a new gateway:
      1. Add it to PROVIDER_CHOICES + DEFAULT_ICONS below
      2. Implement an adapter module (see mall/payments/ folder)
      3. Wire it into checkout via _gateway_for(settings) dispatch
    """
    PROVIDER_CHOICES = [
        ('paystack', 'Paystack'),
    ]
    DEFAULT_ICONS = {
        'paystack': '💳',
    }
    provider      = models.CharField(max_length=20, choices=PROVIDER_CHOICES, default='paystack')
    account_name  = models.CharField(max_length=200, help_text='Display name shown at checkout (e.g. Market Payments)')
    account_number = models.CharField(max_length=100, help_text='Provider Public Key. Paystack: pk_live_... or pk_test_....')
    instructions  = models.TextField(blank=True, help_text='Optional message shown to customers at checkout')
    icon          = models.CharField(max_length=50, blank=True, default='', help_text='Emoji or icon (leave blank for the default)')
    is_active     = models.BooleanField(default=True,
                                        help_text='Tick to make this gateway selectable at checkout. You can have multiple active gateways or just one.')
    # extra_account stores "username::account_number" e.g. "yawill::10832706068375"
    extra_account = models.CharField(max_length=300, blank=True, default='',
                                     help_text='Leave blank for Paystack.')
    private_key   = models.CharField(max_length=500, blank=True, default='',
                                     help_text='Leave blank for Paystack.')
    created_at    = models.DateTimeField(auto_now_add=True)
    updated_at    = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Payment Settings'

    def get_icon(self):
        """Return icon: custom value if set, else default for provider."""
        return self.icon or self.DEFAULT_ICONS.get(self.provider, '💳')

    def __str__(self):
        return f'{self.get_icon()} {self.get_provider_display()} — {self.account_number}'


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='categories/', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    image_url = models.URLField(blank=True, null=True)
    stock = models.PositiveIntegerField(default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # Who uploaded this product (admin or fulfillment officer). Lets the
    # officer portal show "My Products" — everything this officer added.
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='uploaded_products',
        help_text='User (admin or officer) who added this product.',
    )
    
    def __str__(self):
        return self.name

    def avg_rating(self):
        """Average rating across approved reviews. Returns float or None."""
        from django.db.models import Avg
        result = self.reviews.filter(is_approved=True).aggregate(Avg('rating'))['rating__avg']
        return round(result, 1) if result else None

    def review_count(self):
        return self.reviews.filter(is_approved=True).count()

    def rating_breakdown(self):
        """Returns {5:%, 4:%, 3:%, 2:%, 1:%} for the rating bar chart."""
        from django.db.models import Count
        total = self.review_count()
        if not total:
            return {i: 0 for i in range(5, 0, -1)}
        counts = {
            r['rating']: r['count']
            for r in self.reviews.filter(is_approved=True).values('rating').annotate(count=Count('rating'))
        }
        return {i: round(counts.get(i, 0) / total * 100) for i in range(5, 0, -1)}

    # ── Per-branch pricing helpers ──────────────────────────────────────────
    def price_at_branch(self, branch):
        """
        Return the selling price for this product at `branch`, or None if
        the branch doesn't carry it. Falls back to None (NOT self.price)
        because per the strict-stock policy, no row means "not sold here".
        """
        if branch is None:
            return self.price
        bp = self.branch_products.filter(branch=branch, is_available=True).first()
        return bp.price if bp else None

    def stock_at_branch(self, branch):
        """Return per-branch stock, or 0 if not carried."""
        if branch is None:
            return self.stock  # legacy single-stock fallback for un-branched flows
        bp = self.branch_products.filter(branch=branch, is_available=True).first()
        return bp.stock if bp else 0

    def is_available_at_branch(self, branch):
        """True if `branch` carries this product and it's marked available."""
        if branch is None:
            return self.available
        return self.branch_products.filter(branch=branch, is_available=True).exists()

    def branches_carrying(self):
        """Queryset of branches that currently carry this product (in stock + available)."""
        from django.db.models import F
        return (self.branch_products
                .filter(is_available=True, stock__gt=0)
                .select_related('branch')
                .order_by('branch__name'))

GHANA_REGIONS = [
    ('greater_accra', 'Greater Accra Region'),
    ('ashanti',       'Ashanti Region'),
    ('western',       'Western Region'),
    ('western_north', 'Western North Region'),
    ('central',       'Central Region'),
    ('eastern',       'Eastern Region'),
    ('volta',         'Volta Region'),
    ('oti',           'Oti Region'),
    ('bono',          'Bono Region'),
    ('bono_east',     'Bono East Region'),
    ('ahafo',         'Ahafo Region'),
    ('northern',      'Northern Region'),
    ('savannah',      'Savannah Region'),
    ('north_east',    'North East Region'),
    ('upper_east',    'Upper East Region'),
    ('upper_west',    'Upper West Region'),
]

REGION_CHOICES = GHANA_REGIONS
REGION_FEES = {
    'greater_accra': Decimal('15.00'),
    'ashanti':       Decimal('25.00'),
    'western':       Decimal('30.00'),
    'western_north': Decimal('35.00'),
    'central':       Decimal('28.00'),
    'eastern':       Decimal('25.00'),
    'volta':         Decimal('30.00'),
    'oti':           Decimal('40.00'),
    'bono':          Decimal('35.00'),
    'bono_east':     Decimal('38.00'),
    'ahafo':         Decimal('38.00'),
    'northern':      Decimal('45.00'),
    'savannah':      Decimal('50.00'),
    'north_east':    Decimal('50.00'),
    'upper_east':    Decimal('55.00'),
    'upper_west':    Decimal('55.00'),
}



# ─── Delivery fee calculation ─────────────────────────────────────────────────

# Base fee for all home deliveries (covers first 5 km)
DELIVERY_BASE_FEE   = Decimal('10.00')   # GH₵ 10 base
DELIVERY_RATE_PER_KM = Decimal('1.50')   # GH₵ 1.50 per km after 5 km
DELIVERY_FREE_KM    = 5                  # first 5 km included in base fee
DELIVERY_MAX_FEE    = Decimal('80.00')   # cap for very long distances

# Estimated delivery time: 20 min base + 3 min per km
DELIVERY_BASE_MINS  = 20
DELIVERY_MINS_PER_KM = 3


def calculate_delivery_fee(distance_km: float):
    """
    Return (fee: Decimal, eta_minutes: int) for a home delivery.
    distance_km is the straight-line distance from branch to delivery address.
    Uses actual road distance approximation (×1.3 factor for road detours).
    """
    road_km = distance_km * 1.3   # straight-line → estimated road distance
    if road_km <= DELIVERY_FREE_KM:
        fee = DELIVERY_BASE_FEE
    else:
        extra_km = road_km - DELIVERY_FREE_KM
        fee = DELIVERY_BASE_FEE + (Decimal(str(round(extra_km, 2))) * DELIVERY_RATE_PER_KM)
    fee = min(fee, DELIVERY_MAX_FEE).quantize(Decimal('0.01'))
    eta = int(DELIVERY_BASE_MINS + road_km * DELIVERY_MINS_PER_KM)
    return fee, eta


# ─── Branch Model ────────────────────────────────────────────────────────────

class Branch(models.Model):
    BRANCH_TYPE_CHOICES = [
        ('main',    'Main Branch'),
        ('express', 'Express Kiosk'),
        ('agent',   'Mobile Agent Point'),
    ]
    region       = models.CharField(max_length=50, choices=REGION_CHOICES)
    branch_type  = models.CharField(max_length=10, choices=BRANCH_TYPE_CHOICES, default='main')
    name         = models.CharField(max_length=200)
    address      = models.CharField(max_length=300)
    city         = models.CharField(max_length=100)
    phone        = models.CharField(max_length=30, blank=True)
    email        = models.EmailField(blank=True)
    opening_hours = models.CharField(max_length=100, default='Mon–Sat: 8am – 8pm | Sun: 10am – 6pm')
    is_active    = models.BooleanField(default=True)
    landmark     = models.CharField(max_length=200, blank=True, help_text='Nearby landmark for directions')
    latitude     = models.FloatField(null=True, blank=True, help_text='Branch GPS latitude')
    longitude    = models.FloatField(null=True, blank=True, help_text='Branch GPS longitude')
    fulfillment_officer  = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='managed_branches',
        help_text='Fulfillment Officer account assigned to this branch — can confirm orders and hand off to riders/customers.',
    )

    class Meta:
        ordering = ['region', 'name']
        verbose_name_plural = 'Branches'

    def __str__(self):
        return f'{self.name} ({self.get_region_display()})'

    def get_region_display(self):
        return dict(REGION_CHOICES).get(self.region, self.region)

    def shipping_fee(self):
        return REGION_FEES.get(self.region, Decimal('15.00'))

    def distance_to(self, lat: float, lng: float) -> float:
        """
        Haversine formula — returns straight-line distance in km
        between this branch and the given coordinates.
        Returns float('inf') if branch has no coordinates.
        """
        import math
        if self.latitude is None or self.longitude is None:
            return float('inf')
        R = 6371  # Earth radius in km
        dlat = math.radians(lat - self.latitude)
        dlng = math.radians(lng - self.longitude)
        a = (math.sin(dlat / 2) ** 2
             + math.cos(math.radians(self.latitude))
             * math.cos(math.radians(lat))
             * math.sin(dlng / 2) ** 2)
        return R * 2 * math.asin(math.sqrt(a))


class BranchAssignment(models.Model):
    """
    Links a Fulfillment Officer to a Branch with role + approval state.

    Replaces the simple `Branch.fulfillment_officer` FK with a proper
    through-table that supports:
      - one PRIMARY branch per officer (assigned by admin at onboarding)
      - zero or more SECONDARY branches (officer-requested, admin-approved)
      - audit trail of who requested, who decided, and any decision note

    Status flow:
        primary  + approved  — admin assigned at onboarding (the default seed)
        primary  + pending   — admin proposed a primary reassignment, officer accepts
        secondary + pending  — officer requested it, awaiting admin decision
        secondary + approved — admin approved, officer can now act on this branch
        any      + rejected  — admin denied; record kept for audit
        any      + revoked   — was approved, then taken away. Record kept for audit.

    The officer-portal queryset for "branches I can act on" is:
        BranchAssignment.objects.filter(
            officer=user, status='approved', branch__is_active=True
        )
    """
    ROLE_CHOICES = [
        ('primary',   'Primary'),
        ('secondary', 'Secondary'),
    ]
    STATUS_CHOICES = [
        ('pending',  'Pending Approval'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
        ('revoked',  'Revoked'),
    ]

    officer       = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='branch_assignments',
        help_text='The fulfillment officer being assigned to the branch.',
    )
    branch        = models.ForeignKey(
        Branch, on_delete=models.CASCADE, related_name='officer_assignments',
    )
    role          = models.CharField(max_length=10, choices=ROLE_CHOICES, default='secondary')
    status        = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')

    requested_at  = models.DateTimeField(auto_now_add=True)
    requested_by  = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='branch_requests_made',
        help_text='Who initiated this assignment — usually the officer themself, or admin at onboarding.',
    )
    decided_at    = models.DateTimeField(null=True, blank=True)
    decided_by    = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='branch_requests_decided',
        help_text='Admin who approved/rejected/revoked the assignment.',
    )
    decision_note = models.TextField(
        blank=True,
        help_text='Optional note explaining the admin decision (visible to the officer).',
    )

    class Meta:
        unique_together = [('officer', 'branch')]
        ordering = ['-requested_at']
        indexes = [
            models.Index(fields=['officer', 'status']),
            models.Index(fields=['branch', 'status']),
        ]

    def __str__(self):
        return f'{self.officer.username} → {self.branch.name} ({self.get_role_display()}, {self.get_status_display()})'

    @property
    def is_active(self):
        """True when the officer can currently act on this branch."""
        return self.status == 'approved'


# ─── Per-branch product pricing & stock ───────────────────────────────────────

class BranchProduct(models.Model):
    """
    Links a Product to a Branch with the branch-specific price and stock.

    This is the single source of truth for "does branch X carry product Y, and
    if so, at what price + how much stock?". Strict policy:
      - A row exists  → branch sells the product at this price/stock
      - No row exists → branch does NOT carry the product (per project decision)

    Product.price stays as the default headline price shown when no branch is
    known yet (browsing, search, home page). It's only replaced by
    BranchProduct.price during checkout reconciliation.
    """
    product      = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='branch_pricing')
    branch       = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name='stocked_products')
    price        = models.DecimalField(max_digits=10, decimal_places=2,
                                       help_text='Price at this branch (overrides Product.price for this branch only).')
    stock        = models.PositiveIntegerField(default=0,
                                               help_text='Stock available at this branch.')
    is_available = models.BooleanField(default=True,
                                       help_text='Untick to temporarily hide this product at this branch without deleting the row.')
    updated      = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = [('product', 'branch')]
        ordering = ['branch__name', 'product__name']
        indexes = [
            models.Index(fields=['branch', 'is_available']),
        ]
        verbose_name = 'Branch Product'
        verbose_name_plural = 'Branch Products'

    def __str__(self):
        return f'{self.product.name} @ {self.branch.name} — GH₵ {self.price} (stock {self.stock})'


# ─── Order ───────────────────────────────────────────────────────────────────

class Order(models.Model):
    STATUS_CHOICES = [
        ('pending',    'Pending'),
        ('processing', 'Processing'),
        ('shipped',    'Shipped'),
        ('dispatched', 'Dispatched'),
        ('delivered',  'Delivered'),
        ('confirmed',  'Customer Confirmed'),
        ('cancelled',  'Cancelled'),
    ]

    user          = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    branch        = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True, blank=True, related_name='orders')
    created       = models.DateTimeField(auto_now_add=True)
    updated       = models.DateTimeField(auto_now=True)
    status        = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    full_name     = models.CharField(max_length=200)
    email         = models.EmailField()
    phone         = models.CharField(max_length=20)
    address       = models.TextField()
    city          = models.CharField(max_length=100)
    region        = models.CharField(max_length=50, choices=REGION_CHOICES, default='greater_accra')
    zip_code      = models.CharField(max_length=20, blank=True)
    shipping_fee  = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    total_price   = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    FULFILLMENT_CHOICES = [
        ('pickup',   'Branch Pickup'),
        ('delivery', 'Home Delivery'),
    ]
    fulfillment_type  = models.CharField(max_length=10, choices=FULFILLMENT_CHOICES, default='pickup')
    delivery_address  = models.TextField(blank=True, help_text='Full address for home delivery')
    delivery_landmark = models.CharField(
        max_length=200, blank=True,
        help_text='Nearby landmark — e.g. "behind blue water tank, opposite Ghana Methodist Church".',
    )
    # Captured at checkout via the browser geolocation API. Used by the
    # rider's "Navigate to customer" button to deep-link Google Maps with
    # an exact pin instead of a fuzzy address search. Optional — not all
    # devices/permissions allow it; we always fall back to address text.
    delivery_lat      = models.FloatField(null=True, blank=True)
    delivery_lng      = models.FloatField(null=True, blank=True)
    paid               = models.BooleanField(default=False)
    payment_reference  = models.CharField(max_length=100, blank=True, default='', help_text='Paystack/bank transfer reference')
    # FEAT-07: Promo code applied at checkout
    promo_code         = models.ForeignKey('PromoCode', on_delete=models.SET_NULL, null=True, blank=True, related_name='orders')
    discount_amount    = models.DecimalField(max_digits=8, decimal_places=2, default=Decimal('0'))

    def __str__(self):
        return f'Order {self.order_number} by {self.user.username}'

    @property
    def order_number(self):
        """Human-readable order number: #HCM000001, #HCM000042, etc."""
        return f'#HCM{self.id:06d}'

    def get_region_display_name(self):
        return dict(REGION_CHOICES).get(self.region, self.region)

    @property
    def maps_directions_url(self):
        """
        Return a Google Maps URL the rider can tap to start turn-by-turn
        navigation. Uses the GPS pin when available — that's the only way
        to actually get to a Ghanaian house, since most addresses are
        descriptive ("behind the blue tank") rather than geocodable.

        Falls back to a Google Maps SEARCH on the typed address if no GPS
        was captured. Better than nothing, but accuracy depends entirely
        on how Google parses the customer's address text.
        """
        from urllib.parse import quote_plus
        if self.delivery_lat is not None and self.delivery_lng is not None:
            # Directions API deep-link: opens Google Maps app on mobile,
            # web Maps on desktop. travelmode=driving is the right default
            # for riders on motorbikes/cars.
            return (
                f'https://www.google.com/maps/dir/?api=1'
                f'&destination={self.delivery_lat},{self.delivery_lng}'
                f'&travelmode=driving'
            )
        # Fallback: search by typed address + city. Google will best-guess.
        addr = (self.delivery_address or self.address or '').strip()
        if not addr:
            return ''
        query = f'{addr}, {self.city}' if self.city else addr
        return f'https://www.google.com/maps/search/?api=1&query={quote_plus(query)}'

    @property
    def has_gps_pin(self):
        return self.delivery_lat is not None and self.delivery_lng is not None

    def subtotal(self):
        # BUG-03 FIX: Compute subtotal directly from order items so this method
        # is correct even when called before calculate_total() has run (e.g. in
        # unit tests or admin edits). Avoids returning a negative when total_price=0.
        items_total = sum(item.get_total_price() for item in self.items.all())
        if items_total:
            return items_total
        # Fallback for orders where items may have been deleted
        return max(Decimal('0'), self.total_price - self.shipping_fee)

    def calculate_total(self):
        """
        Recompute total_price from the items + shipping_fee, applying any
        promo discount that's been recorded on the order.

        Used by admin tools that edit orders after creation. The original
        checkout flow sets total_price directly from the server-computed
        grand total (which already includes the discount), so this method's
        main job is to keep things consistent if anyone re-runs it later.
        """
        from decimal import Decimal as _D
        subtotal = sum(item.get_total_price() for item in self.items.all())
        self.shipping_fee = REGION_FEES.get(self.region, _D('15.00'))
        # Subtract any promo discount; floor at zero so a generous promo
        # can't produce a negative total.
        discount = self.discount_amount or _D('0')
        self.total_price = max(_D('0'), subtotal + self.shipping_fee - discount)
        self.save()


class OrderItem(models.Model):
    order    = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product  = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price    = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'

    def get_total_price(self):
        return self.price * self.quantity


class Review(models.Model):
    product           = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user              = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews')
    order_item        = models.OneToOneField(
        'OrderItem', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='review',
        help_text='The specific order item this review is for (proves verified purchase)',
    )
    rating            = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 6)])
    title             = models.CharField(max_length=120, blank=True, help_text='Short summary headline')
    comment           = models.TextField()
    is_verified_purchase = models.BooleanField(
        default=False,
        help_text='Auto-set to True when reviewer has a delivered order for this product',
    )
    is_approved       = models.BooleanField(
        default=True,
        help_text='Admins can hide spam or abusive reviews without deleting them',
    )
    helpful_count     = models.PositiveIntegerField(default=0)
    created           = models.DateTimeField(auto_now_add=True)
    updated           = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        # One review per user per product
        unique_together = ('product', 'user')

    def __str__(self):
        return f'{self.user.username} → {self.product.name} ({self.rating}★)'

    def stars_range(self):
        """Return range for template star rendering."""
        return range(1, 6)


class ReviewHelpful(models.Model):
    """Tracks which users have marked a review as helpful (one vote per user per review)."""
    review  = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='helpful_votes')
    user    = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('review', 'user')


# ─── FEAT-01: Wishlist ────────────────────────────────────────────────────────

class WishlistItem(models.Model):
    """One saved product per user. Toggled via AJAX heart icon on product cards."""
    user    = models.ForeignKey(User, on_delete=models.CASCADE, related_name='wishlist')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='wishlisted_by')
    added   = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'product')
        ordering = ['-added']

    def __str__(self):
        return f'{self.user.username} ♥ {self.product.name}'


# ─── FEAT-06: Product Image Gallery ──────────────────────────────────────────

class ProductImage(models.Model):
    """Additional images for a product (beyond the main product.image field)."""
    product    = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='gallery')
    image      = models.ImageField(upload_to='products/gallery/')
    sort_order = models.PositiveIntegerField(default=0, help_text='Lower = shown first')
    alt_text   = models.CharField(max_length=200, blank=True)
    created    = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['sort_order', 'created']

    def __str__(self):
        return f'Image {self.sort_order} for {self.product.name}'


# ─── FEAT-08: Officer Product Upload / CSV Approval ───────────────────────────

class ProductUpload(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending Review'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
        ('partial', 'Partially Approved'),
    ]

    officer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='product_uploads',
        help_text='Fulfillment officer who uploaded this CSV batch.',
    )
    csv_file = models.FileField(
        upload_to='product_uploads/csv/',
        help_text='CSV file with rows: product_name, price, description, sku, category_name, image_filename',
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    total_items = models.PositiveIntegerField(default=0)
    approved_items = models.PositiveIntegerField(default=0)
    rejected_items = models.PositiveIntegerField(default=0)
    reviewed_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='product_uploads_reviewed',
        help_text='Admin who reviewed this product upload batch.',
    )
    review_notes = models.TextField(blank=True)
    reviewed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Product Upload'
        verbose_name_plural = 'Product Uploads'

    def __str__(self):
        return f'ProductUpload #{self.id} by {self.officer.username} ({self.get_status_display()})'

    @property
    def pending_items(self):
        return self.items.filter(status='pending').count()

    def refresh_status(self):
        """Recalculate counts and overall batch status."""
        total = self.items.count()
        approved = self.items.filter(status='approved').count()
        rejected = self.items.filter(status='rejected').count()
        if total == 0:
            status = 'rejected' if self.rejected_items else 'pending'
        elif approved == total:
            status = 'approved'
        elif rejected == total:
            status = 'rejected'
        elif approved > 0 or rejected > 0:
            status = 'partial'
        else:
            status = 'pending'

        update_fields = []
        if self.total_items != total:
            self.total_items = total
            update_fields.append('total_items')
        if self.approved_items != approved:
            self.approved_items = approved
            update_fields.append('approved_items')
        if self.rejected_items != rejected:
            self.rejected_items = rejected
            update_fields.append('rejected_items')
        if self.status != status:
            self.status = status
            update_fields.append('status')
        if update_fields:
            self.save(update_fields=update_fields)


class ProductUploadItem(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending Review'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]

    upload = models.ForeignKey(ProductUpload, on_delete=models.CASCADE, related_name='items')
    product_name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    sku = models.CharField(max_length=100, blank=True)
    category_name = models.CharField(max_length=100, blank=True)
    image_filename = models.CharField(max_length=255, blank=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True, related_name='upload_items')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    rejection_reason = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    approved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Product Upload Item'
        verbose_name_plural = 'Product Upload Items'

    def __str__(self):
        return f'{self.product_name} ({self.get_status_display()})'

    def save(self, *args, **kwargs):
        """Create the product automatically when an item is approved."""
        from django.utils.text import slugify

        was_approved = False
        if self.pk:
            old = ProductUploadItem.objects.filter(pk=self.pk).values('status', 'product').first()
            was_approved = old and old['status'] != 'approved' and self.status == 'approved'
        else:
            was_approved = self.status == 'approved'

        if was_approved and self.product is None:
            cat_name = self.category_name.strip() or 'Uncategorized'
            category, _ = Category.objects.get_or_create(
                name__iexact=cat_name,
                defaults={
                    'name': cat_name,
                    'slug': slugify(cat_name) or f'cat-{self.upload_id}-{int(timezone.now().timestamp())}',
                }
            )
            slug = slugify(self.product_name) or f'product-{self.upload_id}-{self.pk or "new"}'
            base_slug, n = slug, 1
            while Product.objects.filter(slug=slug).exists():
                slug = f'{base_slug}-{n}'
                n += 1

            product = Product.objects.create(
                category=category,
                name=self.product_name,
                slug=slug,
                description=self.description or '',
                price=self.price,
                stock=0,
                available=True,
            )
            self.product = product
            self.approved_at = timezone.now()

        super().save(*args, **kwargs)

        if self.upload_id:
            upload = ProductUpload.objects.filter(pk=self.upload_id).first()
            if upload:
                upload.refresh_status()


class UploadedProductImage(models.Model):
    upload_item = models.ForeignKey(ProductUploadItem, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_uploads/images/')
    alt_text = models.CharField(max_length=200, blank=True)
    sort_order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['sort_order', 'id']

    def __str__(self):
        return f'Image for {self.upload_item.product_name}'


# ─── FEAT-07: Promo Codes ─────────────────────────────────────────────────────

class PromoCode(models.Model):
    DISCOUNT_TYPE_CHOICES = [
        ('percent', 'Percentage (%)'),
        ('fixed',   'Fixed Amount (GH₵)'),
    ]
    code           = models.CharField(max_length=50, unique=True)
    discount_type  = models.CharField(max_length=10, choices=DISCOUNT_TYPE_CHOICES, default='percent')
    discount_value = models.DecimalField(max_digits=8, decimal_places=2,
                                         help_text='Percentage (0–100) or fixed GH₵ amount')
    min_order_value = models.DecimalField(max_digits=8, decimal_places=2, default=Decimal('0'),
                                          help_text='Minimum cart subtotal to activate this code')
    max_uses       = models.PositiveIntegerField(null=True, blank=True,
                                                  help_text='Leave blank for unlimited uses')
    times_used     = models.PositiveIntegerField(default=0)
    valid_from     = models.DateTimeField(default=timezone.now)
    valid_until    = models.DateTimeField(null=True, blank=True)
    is_active      = models.BooleanField(default=True)
    created        = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.code} ({self.get_discount_type_display()} — {self.discount_value})'

    def is_valid(self):
        now = timezone.now()
        if not self.is_active:
            return False, 'This promo code is inactive.'
        if now < self.valid_from:
            return False, 'This promo code is not yet active.'
        if self.valid_until and now > self.valid_until:
            return False, 'This promo code has expired.'
        if self.max_uses is not None and self.times_used >= self.max_uses:
            return False, 'This promo code has reached its usage limit.'
        return True, None

    def calculate_discount(self, subtotal: Decimal) -> Decimal:
        """Return the discount amount to subtract from subtotal."""
        if subtotal < self.min_order_value:
            return Decimal('0')
        if self.discount_type == 'percent':
            return (subtotal * self.discount_value / 100).quantize(Decimal('0.01'))
        return min(self.discount_value, subtotal)


# ─── FEAT-08: Admin Order Notes ───────────────────────────────────────────────

class OrderNote(models.Model):
    """Internal staff notes on an order — not visible to customers."""
    order   = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='notes')
    staff   = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='order_notes')
    note    = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'Note on Order #{self.order_id} by {self.staff}'


# ─── FEAT-NOTIF: In-app Notifications ────────────────────────────────────────

class Notification(models.Model):
    """
    In-app notification for admins and customers.
    - Admin gets notified when a new order is placed.
    - Customer gets notified when admin updates their order status.
    """
    NOTIF_TYPE_CHOICES = [
        ('new_order',        'New Order Placed'),
        ('order_update',     'Order Status Updated'),
        ('stock_alert',      'Low Stock Alert'),
        ('order_cancel',     'Order Cancelled'),
        ('rider_dispatched', 'Rider Dispatched'),
        ('delivery_done',    'Delivery Completed'),
        ('delivery_confirm', 'Customer Confirmed Delivery'),
    ]
    user       = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    notif_type = models.CharField(max_length=20, choices=NOTIF_TYPE_CHOICES)
    title      = models.CharField(max_length=200)
    message    = models.TextField()
    link       = models.CharField(max_length=300, blank=True, help_text='Optional URL to link to')
    is_read    = models.BooleanField(default=False)
    created    = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'[{self.notif_type}] {self.title} → {self.user.username}'



# ─── Rider Delivery ───────────────────────────────────────────────────────────

import secrets as _secrets

class Rider(models.Model):
    """
    A rider in the persistent roster.

    Each rider is created once (by admin or auto-drafted from an officer's
    ad-hoc dispatch) and reused across deliveries. RiderDelivery rows still
    snapshot rider_name/rider_phone at dispatch time so historical orders
    display correctly even if the Rider record is later edited or deleted.

    A rider serves one or many branches via the `branches` M2M. Officers
    assigning a rider only see riders whose branches overlap with the
    branches they're authorized to manage.

    Verification model:
        - is_verified=False — auto-drafted from an ad-hoc dispatch.
                              Still usable, but admin should review.
        - is_verified=True  — admin has reviewed and approved the rider.
                              Picked first in dropdowns, no warning shown.
        - is_active=False   — soft-deactivated. Hidden from dropdowns but
                              past delivery history is preserved.
    """
    VEHICLE_CHOICES = [
        ('motorcycle', 'Motorcycle'),
        ('bicycle',    'Bicycle'),
        ('car',        'Car'),
        ('tricycle',   'Tricycle (Pragya)'),
        ('foot',       'On Foot'),
        ('other',      'Other'),
    ]
    name           = models.CharField(max_length=150)
    phone          = models.CharField(
        max_length=20, unique=True,
        help_text='Primary phone (WhatsApp). Must be unique across all riders.',
    )
    alt_phone      = models.CharField(max_length=20, blank=True)
    vehicle_type   = models.CharField(
        max_length=12, choices=VEHICLE_CHOICES, default='motorcycle',
    )
    license_number = models.CharField(max_length=50, blank=True)
    photo          = models.ImageField(upload_to='riders/', blank=True, null=True)
    branches       = models.ManyToManyField(
        'Branch', related_name='riders', blank=True,
        help_text='Branches this rider is authorized to deliver for.',
    )
    is_active      = models.BooleanField(
        default=True,
        help_text='Inactive riders are hidden from dropdowns but preserved for history.',
    )
    is_verified    = models.BooleanField(
        default=False,
        help_text='Admin has reviewed and approved this rider. '
                  'Riders auto-drafted from ad-hoc dispatches start as unverified.',
    )
    notes          = models.TextField(
        blank=True,
        help_text='Internal notes (e.g. "Reliable, knows East Legon area well").',
    )
    created_by     = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='riders_created',
    )
    created_at     = models.DateTimeField(auto_now_add=True)
    updated_at     = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-is_verified', 'name']
        indexes = [
            models.Index(fields=['phone']),
            models.Index(fields=['is_active', 'is_verified']),
        ]

    def __str__(self):
        return f'{self.name} ({self.phone})'

    @classmethod
    def normalize_phone(cls, raw):
        return normalize_phone(raw)

    @classmethod
    def find_by_phone(cls, raw, *, active_only=False):
        normalized = cls.normalize_phone(raw)
        if not normalized:
            return None
        qs = cls.objects.all()
        if active_only:
            qs = qs.filter(is_active=True)
        for rider in qs:
            if cls.normalize_phone(rider.phone) == normalized:
                return rider
        return None

    def save(self, *args, **kwargs):
        if self.phone:
            self.phone = self.normalize_phone(self.phone)
        super().save(*args, **kwargs)

    @property
    def total_deliveries(self):
        return self.deliveries.count()

    @property
    def successful_deliveries(self):
        return self.deliveries.filter(delivered_at__isnull=False).count()

    @property
    def display_status(self):
        if not self.is_active:
            return 'Inactive'
        if not self.is_verified:
            return 'Unverified'
        return 'Active'


class RiderOTP(models.Model):
    """
    One-time password for rider phone-login.

    The plaintext code is sent to the rider's phone via WhatsApp + SMS.
    Only the SHA-256 hash is stored on the row, so a database leak doesn't
    let attackers reuse outstanding OTPs.

    A new OTP supersedes any older unused OTPs for the same rider so they
    don't accumulate. attempts is incremented on each wrong-code submit;
    after MAX_ATTEMPTS the row locks and the rider must request a new code.
    """
    EXPIRY_MINUTES = 10
    MAX_ATTEMPTS   = 3

    rider        = models.ForeignKey('Rider', on_delete=models.CASCADE, related_name='otps')
    code_hash    = models.CharField(max_length=64, db_index=True,
                                    help_text='SHA-256 of the 6-digit code; never store the plaintext.')
    expires_at   = models.DateTimeField()
    attempts     = models.PositiveSmallIntegerField(default=0)
    used_at      = models.DateTimeField(null=True, blank=True)
    locked       = models.BooleanField(default=False)
    requested_ip = models.GenericIPAddressField(null=True, blank=True)
    created_at   = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        indexes  = [
            models.Index(fields=['rider', 'used_at']),
        ]

    def __str__(self):
        state = 'used' if self.used_at else ('locked' if self.locked else 'pending')
        return f'OTP for {self.rider.phone} ({state})'

    @property
    def is_expired(self):
        from django.utils import timezone as _tz
        return _tz.now() >= self.expires_at

    @property
    def remaining_attempts(self):
        return max(0, self.MAX_ATTEMPTS - self.attempts)

    @classmethod
    def hash_code(cls, code):
        """Hash a plaintext OTP for comparison/storage."""
        import hashlib as _h
        return _h.sha256(code.encode('utf-8')).hexdigest()


class RiderSession(models.Model):
    """
    Authenticated session for a logged-in rider.

    Riders aren't Django Users (they don't have usernames or passwords),
    so we run our own session table. The session token is stored in a
    signed httponly cookie on the rider's phone; this row records the
    binding plus metadata for "active devices" management.

    revoked=True means the session is invalid — used for logout and for
    admin "kick this device". expired sessions are kept until cleaned up
    by a periodic task (so admins can audit recent activity).
    """
    DEFAULT_TTL_DAYS = 30   # "trust this device for 30 days"
    TOKEN_BYTES      = 32   # → 64 hex chars; secrets.token_hex(32)

    rider         = models.ForeignKey('Rider', on_delete=models.CASCADE, related_name='sessions')
    token         = models.CharField(max_length=64, unique=True, editable=False, db_index=True)
    expires_at    = models.DateTimeField(db_index=True)
    last_used_at  = models.DateTimeField(auto_now=True)
    user_agent    = models.CharField(max_length=300, blank=True)
    ip_address    = models.GenericIPAddressField(null=True, blank=True)
    revoked       = models.BooleanField(default=False)
    created_at    = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-last_used_at']
        indexes  = [
            models.Index(fields=['rider', 'revoked', 'expires_at']),
        ]

    def __str__(self):
        return f'Session for {self.rider.name} ({self.token[:8]}…)'

    @property
    def is_active(self):
        from django.utils import timezone as _tz
        return not self.revoked and _tz.now() < self.expires_at

    def save(self, *args, **kwargs):
        if not self.token:
            import secrets as _s
            self.token = _s.token_hex(self.TOKEN_BYTES)
        if not self.expires_at:
            from django.utils import timezone as _tz
            from datetime import timedelta as _td
            self.expires_at = _tz.now() + _td(days=self.DEFAULT_TTL_DAYS)
        super().save(*args, **kwargs)


class RiderDelivery(models.Model):
    """
    Tracks a rider assigned to a delivery order.
    The rider gets a unique token link — no login needed.
    Flow: Officer assigns rider → rider taps "Mark Delivered" → notifications fire.
    """
    order         = models.OneToOneField('Order', on_delete=models.CASCADE, related_name='rider_delivery')

    # Persistent FK to the rider roster (preferred path).
    # Null when this delivery was dispatched ad-hoc to a one-off rider
    # whose details only exist as the snapshot below.
    rider         = models.ForeignKey(
        Rider, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='deliveries',
    )
    is_adhoc      = models.BooleanField(
        default=False,
        help_text='True when dispatched to a one-off rider not in the roster. '
                  'Admin should review these and decide whether to promote the rider to permanent.',
    )

    # Snapshot of rider info at dispatch time. Always populated — for roster
    # riders, copied from the Rider record; for ad-hoc, typed by the officer.
    # Kept as standalone fields so history survives even if the Rider is
    # later renamed, deactivated, or the FK becomes NULL via on_delete.
    rider_name    = models.CharField(max_length=150)
    rider_phone   = models.CharField(max_length=20)

    token         = models.CharField(max_length=64, unique=True, editable=False)
    dispatched_at = models.DateTimeField(auto_now_add=True)
    delivered_at  = models.DateTimeField(null=True, blank=True)
    confirmed_at  = models.DateTimeField(null=True, blank=True)
    # proof note the rider can optionally add
    rider_note    = models.TextField(blank=True)

    class Meta:
        verbose_name = 'Rider Delivery'

    def __str__(self):
        return f'Rider {self.rider_name} — Order #{self.order_id}'

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = _secrets.token_urlsafe(48)
        super().save(*args, **kwargs)

    @property
    def is_delivered(self):
        return self.delivered_at is not None

    @property
    def is_confirmed(self):
        return self.confirmed_at is not None


# ─── FEAT: Order Feedback ─────────────────────────────────────────────────────

class OrderFeedback(models.Model):
    """
    Post-delivery feedback form — separate from product reviews.
    Covers: overall NPS score, delivery speed, packaging, service, photos.
    One feedback per order (enforced via OneToOneField).
    """
    RATING_CHOICES = [(i, i) for i in range(1, 6)]
    NPS_CHOICES    = [(i, str(i)) for i in range(0, 11)]

    order            = models.OneToOneField(Order, on_delete=models.CASCADE, related_name='feedback')
    user             = models.ForeignKey(User,  on_delete=models.CASCADE, related_name='feedback')

    # NPS
    nps_score        = models.PositiveSmallIntegerField(
        choices=NPS_CHOICES,
        help_text='0 = Not at all likely, 10 = Extremely likely to recommend'
    )

    # Category ratings (1–5)
    delivery_rating  = models.PositiveSmallIntegerField(choices=RATING_CHOICES, help_text='Delivery speed')
    packaging_rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES, help_text='Packaging quality')
    service_rating   = models.PositiveSmallIntegerField(choices=RATING_CHOICES, help_text='Customer service')

    # Written comment
    comment          = models.TextField(blank=True, help_text='Optional written feedback')

    # Photos (up to 3)
    photo_1          = models.ImageField(upload_to='feedback/', blank=True, null=True)
    photo_2          = models.ImageField(upload_to='feedback/', blank=True, null=True)
    photo_3          = models.ImageField(upload_to='feedback/', blank=True, null=True)

    created          = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'Feedback on Order #{self.order_id} by {self.user.username} (NPS {self.nps_score})'

    @property
    def nps_label(self):
        if self.nps_score >= 9:  return 'Promoter'
        if self.nps_score >= 7:  return 'Passive'
        return 'Detractor'

    @property
    def avg_category_rating(self):
        return round((self.delivery_rating + self.packaging_rating + self.service_rating) / 3, 1)

    def photos(self):
        return [p for p in [self.photo_1, self.photo_2, self.photo_3] if p]



# ─── Audit Log ───────────────────────────────────────────────────────────────

class AuditLog(models.Model):
    """
    Immutable record of every significant action taken by a staff member
    in the admin panel. Rows are never updated or deleted — only inserted.
    Provides a full, searchable trail for auditors and site owners.
    """

    # Action categories — used for filtering and icon display
    ACTION_CHOICES = [
        # Products
        ('product_create',  'Product Created'),
        ('product_update',  'Product Updated'),
        ('product_delete',  'Product Deleted'),
        # Categories
        ('category_create', 'Category Created'),
        ('category_update', 'Category Updated'),
        ('category_delete', 'Category Deleted'),
        # Orders
        ('order_status',    'Order Status Changed'),
        ('order_note',      'Order Note Added'),
        ('order_delete',    'Order Deleted'),
        ('rider_assign',    'Rider Assigned'),
        # Users
        ('user_staff',      'User Staff Status Toggled'),
        ('user_active',     'User Active Status Toggled'),
        ('user_superuser',  'User Superuser Status Toggled'),
        ('user_delete',     'User Deleted'),
        # Branches
        ('branch_create',   'Branch Created'),
        ('branch_update',   'Branch Updated'),
        ('branch_delete',   'Branch Deleted'),
        # Promo Codes
        ('promo_create',    'Promo Code Created'),
        ('promo_update',    'Promo Code Updated'),
        ('promo_delete',    'Promo Code Deleted'),
        # Reviews
        ('review_toggle',   'Review Visibility Toggled'),
        ('review_delete',   'Review Deleted'),
        # Payment Settings
        ('payment_create',  'Payment Method Created'),
        ('payment_update',  'Payment Method Updated'),
        ('payment_delete',  'Payment Method Deleted'),
        # CSV Import
        ('csv_import',      'CSV Import'),
        # Auth
        ('admin_login',     'Admin Login'),
        ('admin_logout',    'Admin Logout'),
    ]

    actor       = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='audit_logs',
        help_text='Staff member who performed the action.',
    )
    action      = models.CharField(max_length=40, choices=ACTION_CHOICES, db_index=True)
    target_repr = models.CharField(
        max_length=300, blank=True,
        help_text='Human-readable description of the object that was acted on.',
    )
    detail      = models.TextField(
        blank=True,
        help_text='Optional extra context, e.g. old→new values for an edit.',
    )
    ip_address  = models.GenericIPAddressField(null=True, blank=True)
    timestamp   = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering        = ['-timestamp']
        verbose_name    = 'Audit Log Entry'
        verbose_name_plural = 'Audit Log'
        # Prevent any accidental bulk updates/deletes at the ORM level
        default_permissions = ('view',)

    def __str__(self):
        actor = self.actor.username if self.actor else 'unknown'
        return f'[{self.timestamp:%Y-%m-%d %H:%M}] {actor} — {self.get_action_display()}: {self.target_repr}'

    # ── Convenience category helpers ─────────────────────────────────────────

    ACTION_ICONS = {
        'product_create':  '➕', 'product_update':  '✏️',  'product_delete':  '🗑',
        'category_create': '➕', 'category_update': '✏️',  'category_delete': '🗑',
        'order_status':    '🔄', 'order_note':      '📝',  'order_delete':    '🗑',
        'rider_assign':    '🛵',
        'user_staff':      '👤', 'user_active':     '👤',  'user_superuser':  '👤',
        'user_delete':     '🗑',
        'branch_create':   '➕', 'branch_update':   '✏️',  'branch_delete':   '🗑',
        'promo_create':    '➕', 'promo_update':    '✏️',  'promo_delete':    '🗑',
        'review_toggle':   '👁',  'review_delete':   '🗑',
        'payment_create':  '➕', 'payment_update':  '✏️',  'payment_delete':  '🗑',
        'csv_import':      '📥',
        'admin_login':     '🔑', 'admin_logout':    '🚪',
    }

    ACTION_CATEGORY = {
        'product_create': 'product', 'product_update': 'product', 'product_delete': 'product',
        'category_create': 'category', 'category_update': 'category', 'category_delete': 'category',
        'order_status': 'order', 'order_note': 'order', 'order_delete': 'order', 'rider_assign': 'order',
        'user_staff': 'user', 'user_active': 'user', 'user_superuser': 'user', 'user_delete': 'user',
        'branch_create': 'branch', 'branch_update': 'branch', 'branch_delete': 'branch',
        'promo_create': 'promo', 'promo_update': 'promo', 'promo_delete': 'promo',
        'review_toggle': 'review', 'review_delete': 'review',
        'payment_create': 'payment', 'payment_update': 'payment', 'payment_delete': 'payment',
        'csv_import': 'csv',
        'admin_login': 'auth', 'admin_logout': 'auth',
    }

    @property
    def icon(self):
        return self.ACTION_ICONS.get(self.action, '📋')

    @property
    def category(self):
        return self.ACTION_CATEGORY.get(self.action, 'other')


# ─── Stock Reservation ────────────────────────────────────────────────────────

class StockReservation(models.Model):
    """
    Holds stock for a session while the customer is at checkout.
    Released automatically after RESERVATION_MINUTES if not converted to an order.
    Created when a user loads the checkout page; deleted on order placement or expiry.
    """
    RESERVATION_MINUTES = 15

    session_key = models.CharField(max_length=40, db_index=True)
    product     = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reservations')
    quantity    = models.PositiveIntegerField()
    expires_at  = models.DateTimeField(db_index=True)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('session_key', 'product')

    def __str__(self):
        return f'Reservation {self.session_key[:8]}… — {self.quantity}× {self.product.name}'

    @classmethod
    def expire_old(cls):
        """Release expired reservations back to stock. Call from checkout view."""
        from django.utils import timezone as _tz
        from django.db.models import F as _F
        expired = cls.objects.filter(expires_at__lt=_tz.now()).select_related('product')
        for res in expired:
            Product.objects.filter(pk=res.product_id).update(
                stock=_F('stock') + res.quantity
            )
        expired.delete()

    @classmethod
    def release_for_session(cls, session_key):
        """Release all reservations for a session (on order placed or cart cleared)."""
        from django.db.models import F as _F
        reservations = cls.objects.filter(session_key=session_key).select_related('product')
        for res in reservations:
            Product.objects.filter(pk=res.product_id).update(
                stock=_F('stock') + res.quantity
            )
        reservations.delete()


# ─── Admin 2FA ───────────────────────────────────────────────────────────────

class AdminTOTP(models.Model):
    """
    TOTP secret for admin 2FA. One record per staff user.
    The secret is base32-encoded and compatible with Google Authenticator,
    Authy, and any RFC 6238 TOTP app.
    """
    user       = models.OneToOneField(User, on_delete=models.CASCADE, related_name='totp')
    secret     = models.CharField(max_length=64)
    is_enabled = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'TOTP for {self.user.username} ({"on" if self.is_enabled else "off"})'

    def verify(self, token: str) -> bool:
        """Verify a 6-digit TOTP token. Allows ±1 window for clock skew."""
        try:
            import pyotp
            return pyotp.TOTP(self.secret).verify(token.strip(), valid_window=1)
        except Exception:
            return False

    @classmethod
    def get_or_create_secret(cls, user):
        """Return existing TOTP record or create one with a fresh secret."""
        import pyotp
        obj, created = cls.objects.get_or_create(
            user=user,
            defaults={'secret': pyotp.random_base32()},
        )
        return obj


# ─── Promotions (internal banners & sponsored slots) ──────────────────────────

class Promotion(models.Model):
    """
    Internal promotional banners shown to customers — hero carousels,
    cart upsell cards, product-list strip banners. These are NOT third-party
    ads; they only promote things the store already sells or campaigns the
    store is running (e.g. "20% off fashion this weekend", "Free delivery
    above GH₵ 200", "New arrivals this week").
    """
    PLACEMENT_CHOICES = [
        ('home_hero',    'Home — Hero Carousel'),
        ('home_strip',   'Home — Mid-page Strip'),
        ('products_top', 'Product List — Top Banner'),
        ('cart_banner',  'Cart — Upsell Banner'),
        ('checkout',     'Checkout — Sidebar Note'),
    ]

    title       = models.CharField(max_length=120, help_text='Main headline shown to the customer.')
    subtitle    = models.CharField(max_length=240, blank=True, help_text='Optional supporting line below the headline.')
    image       = models.ImageField(upload_to='promotions/', blank=True, null=True,
                                    help_text='Landscape 1200×500 recommended for hero; 1200×250 for strip banners.')
    link_url    = models.CharField(max_length=500, blank=True,
                                   help_text='Where the banner links to. e.g. /products/?category=fashion or a full URL.')
    cta_text    = models.CharField(max_length=40, blank=True, default='Shop Now',
                                   help_text='Button label. Leave blank to hide the button.')
    placement   = models.CharField(max_length=20, choices=PLACEMENT_CHOICES, default='home_hero')
    priority    = models.PositiveIntegerField(default=0,
                                              help_text='Higher priority shows first when multiple promos exist for the same placement.')
    bg_color    = models.CharField(max_length=20, blank=True, default='',
                                   help_text='Optional background colour (CSS value, e.g. #C9A84C). Used when there is no image.')
    text_color  = models.CharField(max_length=20, blank=True, default='',
                                   help_text='Optional text colour.')

    # Scheduling
    starts_at   = models.DateTimeField(null=True, blank=True,
                                       help_text='Leave blank to start immediately.')
    ends_at     = models.DateTimeField(null=True, blank=True,
                                       help_text='Leave blank for no end date.')
    is_active   = models.BooleanField(default=True)

    # Analytics
    impressions = models.PositiveIntegerField(default=0, editable=False)
    clicks      = models.PositiveIntegerField(default=0, editable=False)

    created     = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-priority', '-created']

    def __str__(self):
        return f'{self.get_placement_display()}: {self.title}'

    def is_live(self):
        """True if the promo should actually be shown to customers right now."""
        if not self.is_active:
            return False
        now = timezone.now()
        if self.starts_at and now < self.starts_at:
            return False
        if self.ends_at and now > self.ends_at:
            return False
        return True

    @property
    def ctr(self):
        """Click-through rate as a percentage (0-100)."""
        if not self.impressions:
            return 0
        return round(self.clicks / self.impressions * 100, 2)

    @classmethod
    def active_for(cls, placement):
        """
        Return live (active + within schedule window) promotions for a given
        placement, highest priority first. Used by the promotions_for template tag.
        """
        now = timezone.now()
        qs = cls.objects.filter(is_active=True, placement=placement)
        qs = qs.filter(models.Q(starts_at__isnull=True) | models.Q(starts_at__lte=now))
        qs = qs.filter(models.Q(ends_at__isnull=True)   | models.Q(ends_at__gte=now))
        return qs


# ─── Site Settings (single-row singleton for admin-editable contact info) ─────

class SiteSettings(models.Model):
    """
    Single-row settings table holding site-wide contact & brand info that
    admins should be able to edit without a developer. Always use
    SiteSettings.load() — it guarantees exactly one row exists.
    """
    # Contact info
    phone_primary    = models.CharField(max_length=40, blank=True, default='',
                                        help_text='Main customer phone, e.g. +233 59 178 4205')
    phone_secondary  = models.CharField(max_length=40, blank=True, default='',
                                        help_text='Optional second phone number.')
    email            = models.EmailField(blank=True, default='',
                                         help_text='Customer support email address.')
    whatsapp         = models.CharField(max_length=40, blank=True, default='',
                                        help_text='WhatsApp number. Include country code, no plus sign, e.g. 233591784205')
    hours_weekday    = models.CharField(max_length=100, blank=True, default='Mon–Sat: 8am – 10pm',
                                        help_text='Weekday opening hours shown on contact page.')
    hours_sunday     = models.CharField(max_length=100, blank=True, default='Sun: 10am – 6pm',
                                        help_text='Sunday opening hours.')
    head_office      = models.CharField(max_length=200, blank=True, default='Accra, Ghana',
                                        help_text='Head office address shown on contact page.')

    # Brand assets — uploaded through the admin Site Settings page.
    # Falls back to the static files at /static/images/logo.png and
    # /static/images/og-image.jpg if no upload is present.
    logo             = models.ImageField(upload_to='branding/', blank=True, null=True,
                                         help_text='Square logo (recommended 512×512 PNG with transparent background). Shown in the navbar and search engine results. Falls back to /static/images/logo.png if blank.')
    og_image         = models.ImageField(upload_to='branding/', blank=True, null=True,
                                         help_text='Social share preview banner (recommended 1200×630 JPG/PNG). Shown when your site link is pasted on WhatsApp/Facebook/Twitter. Falls back to /static/images/og-image.jpg if blank.')

    # Social media (optional, shown wherever you wire them up)
    facebook_url     = models.URLField(blank=True, default='')
    instagram_url    = models.URLField(blank=True, default='')
    twitter_url      = models.URLField(blank=True, default='')
    tiktok_url       = models.URLField(blank=True, default='')

    # WhatsApp notifications via Meta Cloud API
    # Fill these in the admin Site Settings page to enable WhatsApp alerts.
    # Leave any blank to disable WhatsApp sending (the order flow still works
    # normally — only email goes out).
    wa_enabled              = models.BooleanField(default=False,
                                                  help_text='Master switch. Turn on to send WhatsApp alerts.')
    wa_phone_number_id      = models.CharField(max_length=80, blank=True, default='',
                                               help_text='From Meta dashboard → WhatsApp → API Setup → "Phone number ID".')
    wa_access_token         = models.CharField(max_length=300, blank=True, default='',
                                               help_text='Meta access token. Use a permanent system-user token for production.')
    wa_admin_number         = models.CharField(max_length=40, blank=True, default='',
                                               help_text='Admin WhatsApp number that gets new-order alerts. Digits only with country code, e.g. 233591784205')
    wa_template_new_order   = models.CharField(max_length=80, blank=True, default='order_confirmation',
                                               help_text='Meta template name sent to the CUSTOMER on order placement. Must be pre-approved in Meta Business.')
    wa_template_status      = models.CharField(max_length=80, blank=True, default='order_status_update',
                                               help_text='Template sent to the customer when admin changes order status.')
    wa_notify_customer      = models.BooleanField(default=True,
                                                  help_text='Send WhatsApp to customers on new orders and status changes.')
    wa_notify_admin         = models.BooleanField(default=True,
                                                  help_text='Send WhatsApp alert to admin number on every new order.')

    # ── Messaging via Nalo (SMS + OTP) ────────────────────────────────────────
    # Nalo is the primary SMS/OTP provider. Fill these in Panel → Site Settings
    # to switch it on. Takes priority over Tiliow when enabled.
    nalo_enabled      = models.BooleanField(default=False,
                                            help_text='Master switch for Nalo SMS messaging (OTP + alerts).')
    nalo_username     = models.CharField(max_length=150, blank=True, default='',
                                         help_text='Nalo SMS API username from your Nalo dashboard.')
    nalo_password     = models.CharField(max_length=300, blank=True, default='',
                                         help_text='Nalo SMS API password / auth key from your Nalo dashboard.')
    nalo_api_url      = models.CharField(max_length=300, blank=True,
                                         default='https://sms.nalosolutions.com/smsbackend/clientapi/Resl_Nalo/send-message/',
                                         help_text='Nalo SMS endpoint. Leave as default unless Nalo gives you a different one.')
    nalo_sender_id    = models.CharField(max_length=11, blank=True, default='',
                                         help_text='Approved sender ID shown to recipients (max 11 characters), e.g. HoneyCave.')

    # ── Messaging via Tiliow (WhatsApp + SMS + OTP) ──────────────────────────
    # Secondary messaging provider, used when Nalo isn't enabled. One key
    # delivers WhatsApp, SMS and OTP codes to customers, admins, officers and
    # riders. Fill these in Panel → Site Settings to switch messaging on.
    tiliow_enabled    = models.BooleanField(default=False,
                                            help_text='Master switch for Tiliow messaging (WhatsApp + SMS + OTP).')
    tiliow_api_key    = models.CharField(max_length=300, blank=True, default='',
                                         help_text='Tiliow API key / bearer token from your Tiliow dashboard.')
    tiliow_api_url    = models.CharField(max_length=300, blank=True,
                                         default='https://api.tiliow.com/v1/messages',
                                         help_text='Tiliow messages endpoint. Leave as default unless Tiliow tells you otherwise.')
    tiliow_sender_id  = models.CharField(max_length=80, blank=True, default='',
                                         help_text='Optional sender ID / approved WhatsApp sender shown to recipients.')

    # ── Maintenance Mode ──────────────────────────────────────────────────────
    maintenance_mode    = models.BooleanField(
        default=False,
        help_text='When ON, all visitors (except staff) see the maintenance page. Staff can still browse normally.'
    )
    maintenance_message = models.TextField(
        blank=True,
        default='We are performing scheduled maintenance. We will be back shortly!',
        help_text='Message shown on the maintenance page.'
    )
    maintenance_bypass_token = models.CharField(
        max_length=80,
        blank=True,
        default='',
        help_text='Optional secret token. Visitors who add ?bypass=TOKEN to any URL can preview the site even during maintenance.'
    )

    updated          = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Site Settings'
        verbose_name_plural = 'Site Settings'

    def __str__(self):
        return 'Site Settings'

    def save(self, *args, **kwargs):
        # Enforce singleton — there can be only one row.
        self.pk = 1
        super().save(*args, **kwargs)
        # Invalidate the maintenance middleware's in-process cache so toggling
        # maintenance mode in the admin takes effect on the very next request
        # instead of waiting out the 15s cache TTL.
        try:
            from .middleware import MaintenanceModeMiddleware
            MaintenanceModeMiddleware._cache_ts = 0
        except Exception:
            pass

    def delete(self, *args, **kwargs):
        # Prevent deletion — admins should edit, not delete.
        pass

    @classmethod
    def load(cls):
        """Return the single settings row, creating it with defaults if missing."""
        obj, _ = cls.objects.get_or_create(pk=1)
        return obj


# ─── Officer Upload Access — payment / approval gate ──────────────────────────

class OfficerUploadRequest(models.Model):
    """
    An officer's request for permission to upload products, plus the admin's
    decision. The admin chooses one of two paths:

      1. PAY-FIRST: admin sets a price (amount) → status 'payment_required'.
         The officer pays via Paystack; on verified payment → status 'paid'
         and their profile.can_upload_products is switched on.

      2. FREE GO-AHEAD: admin approves with no charge → status 'approved_free'
         and profile.can_upload_products is switched on immediately.

    The effective gate stays UserProfile.can_upload_products (so existing
    enforcement is unchanged); this model just records the request/decision
    and is what flips that flag on.
    """
    STATUS_CHOICES = [
        ('pending',          'Pending admin review'),
        ('payment_required', 'Payment required'),
        ('paid',             'Paid — access granted'),
        ('approved_free',    'Approved free — access granted'),
        ('rejected',         'Rejected'),
    ]

    officer        = models.ForeignKey(User, on_delete=models.CASCADE,
                                       related_name='upload_requests')
    status         = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    amount         = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True,
                                         help_text='Price (GH₵) the admin set for upload access. Only for the pay-first path.')
    payment_reference = models.CharField(max_length=120, blank=True, default='')
    amount_paid    = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    admin_note     = models.CharField(max_length=300, blank=True, default='')

    decided_by     = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                       related_name='decided_upload_requests')
    decided_at     = models.DateTimeField(null=True, blank=True)
    created        = models.DateTimeField(auto_now_add=True)
    updated        = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.officer.username} — {self.get_status_display()}'

    @property
    def access_granted(self):
        return self.status in ('paid', 'approved_free')


# ─── Chain of Custody — Handoff Codes ─────────────────────────────────────────

class HandoffCode(models.Model):
    """
    Tracks one handoff in the chain-of-custody flow for an order.

    Stages (delivery order):
        admin_to_keeper       Admin → Fulfillment Officer. Admin generates code, fulfillment officer enters it.
        keeper_to_rider       Fulfillment Officer → Rider. Fulfillment Officer auto-issues code, rider enters it.
        rider_to_customer     Rider → Customer. Rider shows code, customer enters it.

    Stages (pickup order — no rider):
        admin_to_keeper       Same as above.
        keeper_to_customer    Fulfillment Officer → Customer. Fulfillment Officer shows code, customer types it on collection.

    Lifecycle:
        Generated  → code is issued, sent via in-app/WhatsApp/SMS
        Verified   → receiver entered correct code, used_at is set
        Locked     → 3 wrong attempts, admin alerted, used_at stays null
        Expired    → 10 minutes passed without verification (admin can regenerate)
    """
    STAGE_CHOICES = [
        ('admin_to_officer',   'Admin → Fulfillment Officer'),
        ('officer_to_rider',   'Fulfillment Officer → Rider'),
        ('rider_to_customer', 'Rider → Customer'),
        ('officer_to_customer','Fulfillment Officer → Customer (Pickup)'),
    ]
    EXPIRY_MINUTES = 120   # 2 hours — enough for real-world shop operations
    MAX_ATTEMPTS = 3

    order        = models.ForeignKey('Order', on_delete=models.CASCADE, related_name='handoff_codes')
    stage        = models.CharField(max_length=24, choices=STAGE_CHOICES)
    code         = models.CharField(max_length=6, db_index=True,
                                    help_text='6-digit numeric code shown to the issuer and entered by the receiver.')
    attempts     = models.PositiveIntegerField(default=0)
    locked       = models.BooleanField(default=False,
                                       help_text='Set to True after MAX_ATTEMPTS wrong tries. Requires admin unlock.')
    created_at   = models.DateTimeField(auto_now_add=True)
    used_at      = models.DateTimeField(null=True, blank=True)
    used_by      = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                     related_name='handoff_codes_used',
                                     help_text='User who entered the correct code (if logged in).')
    issued_to_label = models.CharField(max_length=120, blank=True, default='',
                                       help_text='Free-text label for who the code was sent to (e.g. rider name, customer name) — useful when no User account exists.')

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['order', 'stage']),
        ]

    def __str__(self):
        return f'{self.get_stage_display()} for Order {self.order_id} ({self.code})'

    @property
    def is_expired(self):
        if self.used_at:
            return False
        return (timezone.now() - self.created_at).total_seconds() > self.EXPIRY_MINUTES * 60

    @property
    def is_verified(self):
        return self.used_at is not None

    @property
    def is_active(self):
        """True when the code can still be used to verify a handoff."""
        return not self.locked and not self.is_verified and not self.is_expired

    @property
    def remaining_attempts(self):
        return max(0, self.MAX_ATTEMPTS - self.attempts)

    @property
    def seconds_until_expiry(self):
        if self.used_at:
            return 0
        delta = (self.created_at + timedelta(minutes=self.EXPIRY_MINUTES)) - timezone.now()
        return max(0, int(delta.total_seconds()))

    @property
    def qr_svg(self):
        """Inline SVG QR code encoding `self.code` — for templates."""
        # Lazy import to avoid loading qrcode at module-import time.
        from .handoff import qr_svg_for_code
        return qr_svg_for_code(self.code)


