# Generated by Django 4.2.29 on 2026-03-11 12:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_paymentsettings_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Optional URL to link to', max_length=300),
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional written feedback'),
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='delivery_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Delivery speed'),
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='packaging_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Packaging quality'),
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='service_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Customer service'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower = shown first'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Percentage (0–100) or fixed GH₵ amount', max_digits=8),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses', null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Minimum cart subtotal to activate this code', max_digits=8),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admins can hide spam or abusive reviews without deleting them'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, help_text='Auto-set to True when reviewer has a delivered order for this product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(blank=True, help_text='The specific order item this review is for (proves verified purchase)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='mall.orderitem'),
        ),
    ]
