# Generated by Django 4.2.30 on 2026-04-19 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mall', '0016_order_payment_reference_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Staff member who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='detail',
            field=models.TextField(blank=True, help_text='Optional extra context, e.g. old→new values for an edit.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_repr',
            field=models.CharField(blank=True, help_text='Human-readable description of the object that was acted on.', max_length=300),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='instructions',
            field=models.TextField(blank=True, help_text='Optional message shown to customers at checkout'),
        ),
    ]
