# Generated by Django 4.2.30 on 2026-04-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0017_product_image_url_alter_auditlog_actor_and_more'),
        ('mall', '0019_sitesettings_whatsapp'),
    ]

    operations = [
    ]
