# Generated by Django 5.2.13 on 2026-05-03 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0026_storekeeper_to_fulfillment_officer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='branchproduct',
            new_name='mall_branch_branch__5e2783_idx',
            old_name='mall_branch_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='handoffcode',
            new_name='mall_handof_order_i_05d069_idx',
            old_name='mall_handof_order_i_a8f1d2_idx',
        ),
        migrations.AlterField(
            model_name='branch',
            name='fulfillment_officer',
            field=models.ForeignKey(blank=True, help_text='Fulfillment Officer account assigned to this branch — can confirm orders and hand off to riders/customers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branchproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='handoffcode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_fulfillment_officer',
            field=models.BooleanField(default=False, help_text='Marks this user as a branch fulfillment officer. They can log in to the fulfillment officer portal and process orders for the branch they manage.'),
        ),
    ]
