# Generated by Django 5.2.13 on 2026-05-04 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0027_auto_field_drift_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riderdelivery',
            name='is_adhoc',
            field=models.BooleanField(default=False, help_text='True when dispatched to a one-off rider not in the roster. Admin should review these and decide whether to promote the rider to permanent.'),
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(help_text='Primary phone (WhatsApp). Must be unique across all riders.', max_length=20, unique=True)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('tricycle', 'Tricycle (Pragya)'), ('foot', 'On Foot'), ('other', 'Other')], default='motorcycle', max_length=12)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='riders/')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive riders are hidden from dropdowns but preserved for history.')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin has reviewed and approved this rider. Riders auto-drafted from ad-hoc dispatches start as unverified.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes (e.g. "Reliable, knows East Legon area well").')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, help_text='Branches this rider is authorized to deliver for.', related_name='riders', to='mall.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_verified', 'name'],
            },
        ),
        migrations.AddField(
            model_name='riderdelivery',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='mall.rider'),
        ),
        migrations.CreateModel(
            name='BranchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='secondary', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, help_text='Optional note explaining the admin decision (visible to the officer).')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_assignments', to='mall.branch')),
                ('decided_by', models.ForeignKey(blank=True, help_text='Admin who approved/rejected/revoked the assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(help_text='The fulfillment officer being assigned to the branch.', on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, help_text='Who initiated this assignment — usually the officer themself, or admin at onboarding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['officer', 'status'], name='mall_branch_officer_a15e09_idx'), models.Index(fields=['branch', 'status'], name='mall_branch_branch__842321_idx')],
                'unique_together': {('officer', 'branch')},
            },
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['phone'], name='mall_rider_phone_ce78db_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['is_active', 'is_verified'], name='mall_rider_is_acti_9665e2_idx'),
        ),
    ]
