# Generated by Django 5.2.13 on 2026-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0030_riderotp_ridersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark — e.g. "behind blue water tank, opposite Ghana Methodist Church".', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
