# Generated by Django 5.2.13 on 2026-05-05 09:01
# Hand-edited to add a one-shot backfill so any in-flight OTPs created
# before the deploy keep working through their 10-minute validity window.

import hashlib
from django.db import migrations, models


def backfill_hashes(apps, schema_editor):
    """
    Populate code_hash from plaintext code for existing rows.
    Idempotent: skips rows that already have code_hash set, and rows
    whose `code` is empty.
    """
    OTPVerification = apps.get_model('mall', 'OTPVerification')
    qs = OTPVerification.objects.filter(code_hash='').exclude(code='')
    for row in qs:
        row.code_hash = hashlib.sha256(row.code.encode('utf-8')).hexdigest()
        row.save(update_fields=['code_hash'])


def noop(apps, schema_editor):
    """Reverse: no-op. Plaintext is still on the row for legacy rows."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0031_order_delivery_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='code_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of the 6-digit OTP. Authoritative.', max_length=64),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='code',
            field=models.CharField(blank=True, default='', help_text='DEPRECATED: kept for backward-compat with pre-hash rows. New rows leave this empty.', max_length=6),
        ),
        migrations.RunPython(backfill_hashes, noop),
    ]
