# Generated by Django 5.2.14 on 2026-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0034_sitesettings_maintenance_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_bypass_token',
            field=models.CharField(blank=True, default='', help_text='Optional secret token. Visitors who add ?bypass=TOKEN to any URL can preview the site even during maintenance.', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='When ON, all visitors (except staff) see the maintenance page. Staff can still browse normally.'),
        ),
    ]
