# Generated by Django 5.2.14 on 2026-05-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0035_alter_sitesettings_maintenance_bypass_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettings',
            name='account_number',
            field=models.CharField(help_text='Provider Public Key. Paystack: pk_live_... or pk_test_....', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=20),
        ),
    ]
