# Generated by Django 5.2.14 on 2026-05-28 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0037_merge_paymentsettings_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_upload_products',
            field=models.BooleanField(default=False, help_text='Allow this fulfillment officer to add/upload products and images from the officer portal.'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='extra_account',
            field=models.CharField(blank=True, default='', help_text='Leave blank for Paystack.', max_length=300),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Emoji or icon (leave blank for the default)', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Tick to make this gateway selectable at checkout. You can have multiple active gateways or just one.'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='private_key',
            field=models.CharField(blank=True, default='', help_text='Leave blank for Paystack.', max_length=500),
        ),
        migrations.CreateModel(
            name='ProductUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(help_text='CSV file with rows: product_name, price, description, sku, category_name, image_filename', upload_to='product_uploads/csv/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partially Approved')], default='pending', max_length=10)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('approved_items', models.PositiveIntegerField(default=0)),
                ('rejected_items', models.PositiveIntegerField(default=0)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(help_text='Fulfillment officer who uploaded this CSV batch.', on_delete=django.db.models.deletion.CASCADE, related_name='product_uploads', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this product upload batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_uploads_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Upload',
                'verbose_name_plural': 'Product Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductUploadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_items', to='mall.product')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mall.productupload')),
            ],
            options={
                'verbose_name': 'Product Upload Item',
                'verbose_name_plural': 'Product Upload Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_uploads/images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('upload_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mall.productuploaditem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
