# Generated by Django 5.2.14 on 2026-05-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0038_userprofile_can_upload_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tiliow_api_key',
            field=models.CharField(blank=True, default='', help_text='Tiliow API key / bearer token from your Tiliow dashboard.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiliow_api_url',
            field=models.CharField(blank=True, default='https://api.tiliow.com/v1/messages', help_text='Tiliow messages endpoint. Leave as default unless Tiliow tells you otherwise.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiliow_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for Tiliow messaging (WhatsApp + SMS + OTP).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiliow_sender_id',
            field=models.CharField(blank=True, default='', help_text='Optional sender ID / approved WhatsApp sender shown to recipients.', max_length=80),
        ),
    ]
