# Generated by Django 5.2.14 on 2026-05-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0039_sitesettings_tiliow_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_products',
            field=models.ManyToManyField(blank=True, help_text='Products this fulfillment officer is responsible for processing/handling.', related_name='assigned_officers', to='mall.product'),
        ),
    ]
