# Generated by Django 5.2.14 on 2026-08-17 02:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0047_shipmentbooking_shipping_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riderotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('withdrawal', 'Withdrawal Confirmation')], default='login', max_length=12),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reserve_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Percentage of each seller payout held back in reserve for refunds/disputes/chargebacks.', max_digits=4),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rider_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='Platform commission charged to riders on delivery fees. Recommended range 7.00–8.00.', max_digits=4),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seller_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Platform commission charged to sellers on delivered orders. Recommended range 5.00–6.00.', max_digits=4),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='withdrawal_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Flat GH₵ fee charged per withdrawal. Waived automatically for premium sellers.', max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='withdrawal_hold_hours_new',
            field=models.PositiveIntegerField(default=48, help_text="Hours a NEW or high-risk seller/rider must wait before a delivered order's earnings become available for withdrawal."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='withdrawal_hold_hours_trusted',
            field=models.PositiveIntegerField(default=24, help_text='Hours a TRUSTED (admin-verified) seller/rider must wait before earnings become available.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='withdrawal_min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Minimum GH₵ amount a seller/rider can cash out at once.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Sign Up Verification'), ('password_reset', 'Password Reset'), ('withdrawal', 'Seller Withdrawal Confirmation')], default='signup', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('boost', 'Boost — 3 days'), ('spotlight', 'Spotlight — 7 days'), ('featured', 'Featured — 14 days')], default='boost', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='mall.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_boosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('seller', 'Seller'), ('rider', 'Rider')], max_length=10)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Earnings still inside the withdrawal hold window.', max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Earnings cleared and ready to cash out.', max_digits=12)),
                ('withdrawn_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reserve_held', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Held back for refunds/disputes/chargebacks — excluded from available_balance.', max_digits=12)),
                ('is_trusted', models.BooleanField(default=False, help_text='Admin-verified, established account. Shortens the withdrawal hold. New sellers/riders start False.')),
                ('is_frozen', models.BooleanField(default=False, help_text='Admin freeze — blocks new withdrawal requests while a dispute is investigated. Earnings keep accruing.')),
                ('fee_waived', models.BooleanField(default=False, help_text='Premium account — waives the flat withdrawal fee.')),
                ('payout_method', models.CharField(blank=True, choices=[('bank', 'Bank'), ('momo', 'Mobile Money')], default='', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=150)),
                ('momo_network', models.CharField(blank=True, default='', help_text='MTN, Telecel, or AirtelTigo', max_length=20)),
                ('momo_number', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='mall.rider')),
                ('seller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross amount requested, before fee.', max_digits=12)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='amount - fee_charged — what is actually transferred.', max_digits=12)),
                ('method', models.CharField(choices=[('bank', 'Bank'), ('momo', 'Mobile Money')], max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('account_name', models.CharField(blank=True, default='', max_length=150)),
                ('momo_network', models.CharField(blank=True, default='', max_length=20)),
                ('unique_reference', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending_otp', 'Awaiting OTP Confirmation'), ('processing', 'Processing (sent to Paystack)'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed — funds returned to wallet')], default='pending_otp', max_length=12)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('paystack_transfer_code', models.CharField(blank=True, default='', max_length=100)),
                ('paystack_recipient_code', models.CharField(blank=True, default='', max_length=100)),
                ('paystack_status', models.CharField(blank=True, default='', max_length=30)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=300)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='mall.wallet')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale_credit', 'Sale Credit'), ('commission_debit', 'Commission Debit'), ('boost_debit', 'Product Boost Payment'), ('withdrawal_debit', 'Withdrawal'), ('withdrawal_fee', 'Withdrawal Fee'), ('reserve_hold', 'Reserve Held'), ('reserve_release', 'Reserve Released'), ('refund_debit', 'Refund / Chargeback'), ('reversal', 'Reversal'), ('adjustment', 'Manual Admin Adjustment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending (in hold)'), ('available', 'Available'), ('withdrawn', 'Withdrawn'), ('reversed', 'Reversed')], default='available', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed amount — credits positive, debits negative.', max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('available_at', models.DateTimeField(blank=True, help_text='When a pending credit clears the withdrawal hold.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Set only for manual admin adjustments — audit trail of who touched a wallet by hand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_adjustments_made', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='mall.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mall.wallet')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='mall.withdrawalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_type', 'seller'), ('rider__isnull', True), ('seller__isnull', False)), models.Q(('owner_type', 'rider'), ('rider__isnull', False), ('seller__isnull', True)), _connector='OR'), name='wallet_owner_matches_type'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['wallet', 'status'], name='mall_withdr_wallet__8f682c_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'status'], name='mall_wallet_wallet__4f9763_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='mall_wallet_wallet__6c180e_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['order'], name='mall_wallet_order_i_980f38_idx'),
        ),
    ]
