# Generated by Django 5.2.14 on 2026-08-18 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0048_wallet_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_products', to='mall.product'),
        ),
    ]
