# Generated by Django 5.2.14 on 2026-08-18 01:17
#
# NOTE: on the live Render database, `nalo_auth_key` already exists on
# mall_sitesettings (added outside of Django's migration history at some
# point before this migration was written) — a plain AddField blows up
# with "column already exists". The AddField below is wrapped in
# SeparateDatabaseAndState so Django's migration state gets the field
# (satisfying makemigrations/model checks) while the actual DB change is
# a RunPython step that checks column existence first via the schema
# introspector — safe whether or not the column is already there, and
# works on both Postgres (prod) and SQLite (local dev).
from django.db import migrations, models


def add_nalo_auth_key_if_missing(apps, schema_editor):
    table = 'mall_sitesettings'
    column = 'nalo_auth_key'
    existing = {
        f.name for f in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), table,
        )
    }
    if column in existing:
        return  # already there — nothing to do
    field = models.CharField(blank=True, default='', max_length=300)
    field.set_attributes_from_name(column)
    schema_editor.add_field(
        apps.get_model('mall', 'SiteSettings'),
        field,
    )


def remove_nalo_auth_key(apps, schema_editor):
    table = 'mall_sitesettings'
    column = 'nalo_auth_key'
    existing = {
        f.name for f in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), table,
        )
    }
    if column not in existing:
        return
    field = models.CharField(blank=True, default='', max_length=300)
    field.set_attributes_from_name(column)
    schema_editor.remove_field(
        apps.get_model('mall', 'SiteSettings'),
        field,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0049_branchproduct_related_name_fix'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='sitesettings',
                    name='nalo_auth_key',
                    field=models.CharField(blank=True, default='', help_text='Nalo auth key (alternative to username/password).', max_length=300),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_nalo_auth_key_if_missing, remove_nalo_auth_key),
            ],
        ),
        migrations.AlterField(
            model_name='officeruploadrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
