# Generated by Django 5.2.14 on 2026-09-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0053_riderdelivery_seller_riderdelivery_shipping_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapplication',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Store GPS latitude', null=True),
        ),
        migrations.AddField(
            model_name='storeapplication',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Store GPS longitude', null=True),
        ),
        migrations.AddField(
            model_name='storeapplication',
            name='nearby_landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark to help admin locate the store, e.g. "Opposite Shell filling station"', max_length=200),
        ),
    ]
