# Generated by Django 5.2.14 on 2026-09-09 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0054_storeapplication_latitude_storeapplication_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('damaged', 'Arrived Damaged'), ('wrong_item', 'Wrong Item Received'), ('not_working', "Doesn't Work / Defective"), ('not_as_described', 'Not As Described'), ('changed_mind', 'Changed My Mind'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text="Customer's own words on what went wrong")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='returns/photos/')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved — Awaiting Item Pickup'), ('rejected', 'Rejected'), ('item_received', 'Item Received'), ('refunded', 'Refunded')], default='requested', max_length=20)),
                ('decision_note', models.CharField(blank=True, default='', max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_returns', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='mall.orderitem')),
            ],
            options={
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'requested')), fields=('order_item',), name='one_pending_return_per_item')],
            },
        ),
    ]
