# Generated by Django 5.2.14 on 2026-09-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0056_userprofile_can_send_campaigns_emailcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
