# Generated by Django 5.2.14 on 2026-09-11 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0057_userprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('sale_credit', 'Sale Credit'), ('commission_debit', 'Commission Debit'), ('boost_debit', 'Product Boost Payment'), ('withdrawal_debit', 'Withdrawal'), ('withdrawal_fee', 'Withdrawal Fee'), ('reserve_hold', 'Reserve Held'), ('reserve_release', 'Reserve Released'), ('refund_debit', 'Refund / Chargeback'), ('reversal', 'Reversal'), ('adjustment', 'Manual Admin Adjustment'), ('deposit_credit', 'Wallet Deposit')], max_length=20),
        ),
        migrations.CreateModel(
            name='WalletDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
