# Generated by Django 5.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0058_alter_wallettransaction_type_walletdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapplication',
            name='seller_code',
            field=models.CharField(blank=True, help_text='e.g. HC-SLR-000125 — generated on approval', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storeapplication',
            name='store_slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
