# Generated by Django 5.2.14 on 2026-09-12 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0059_storeapplication_seller_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='chargeable_party',
            field=models.CharField(blank=True, choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('platform', 'HoneyCave'), ('rider', 'Rider (liability)'), ('none', 'No extra charge')], max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='rider_evidence_photo',
            field=models.ImageField(blank=True, null=True, upload_to='returns/rider_photos/'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='rider_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='waiting_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('damaged', 'Arrived Damaged'), ('wrong_item', 'Wrong Item Received'), ('not_working', "Doesn't Work / Defective"), ('not_as_described', 'Not As Described'), ('changed_mind', 'Changed My Mind'), ('other', 'Other'), ('misleading_listing', "Seller's Listing Was Misleading"), ('system_error', 'HoneyCave System/Order Error'), ('wrong_address', 'Rider Delivered To Wrong Address')], max_length=20),
        ),
        migrations.CreateModel(
            name='SellerIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('penalty_level', models.PositiveSmallIntegerField(default=1)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.returnrequest')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('target_min', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('target_max', models.DecimalField(decimal_places=2, default=300, max_digits=8)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
