# Generated by Django 5.2.14 on 2026-09-12 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0059_storeapplication_seller_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_item', 'Seller supplied wrong product/size/quantity'), ('misleading_listing', "Seller's listing was misleading"), ('system_error', 'HoneyCave system/order error'), ('buyer_changed_mind', 'Buyer ordered incorrectly / changed mind'), ('wrong_address', 'Rider delivered to wrong address'), ('rider_damage', 'Product damaged by rider'), ('seller_damage', 'Product already damaged/poorly packaged by seller')], max_length=30)),
                ('buyer_evidence_photo', models.ImageField(upload_to='rejections/buyer/')),
                ('rider_evidence_photo', models.ImageField(blank=True, null=True, upload_to='rejections/rider/')),
                ('chargeable_party', models.CharField(blank=True, choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('platform', 'HoneyCave'), ('rider', 'Rider (liability)'), ('none', 'No extra charge')], max_length=20)),
                ('return_confirmed_by_seller', models.BooleanField(default=False)),
                ('return_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('waiting_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='mall.order')),
            ],
        ),
        migrations.CreateModel(
            name='SellerIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('penalty_level', models.PositiveSmallIntegerField(default=1)),
                ('order_rejection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.orderrejection')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('target_min', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('target_max', models.DecimalField(decimal_places=2, default=300, max_digits=8)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
