# Generated by Django 5.2.14 on 2026-09-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0060_returnrequest_chargeable_party_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerReserve',
        ),
    ]
