# Generated by Django 5.2.14 on 2026-09-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0061_delete_sellerreserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='buyer_fee_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
