# Generated by Django 5.2.14 on 2026-09-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0062_returnrequest_buyer_fee_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Seller is suspended due to repeated incidents (wrong items, damaged goods, etc). Suspended sellers should not have their products shown at checkout -- storefront enforcement is a separate follow-up.'),
        ),
    ]
