# Generated by Django 5.2.14 on 2026-09-17 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0066_wallettransaction_rider_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # NOTE: the 'email' column already exists on mall_rider in the live
        # database (added manually/ad-hoc in an earlier session, never
        # recorded in migration history). Wrapped in SeparateDatabaseAndState
        # so Django's migration state catches up to match reality without
        # re-running an ADD COLUMN that would collide with the existing one.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='rider',
                    name='email',
                    field=models.EmailField(blank=True, help_text='Optional. Lets the rider log in with email instead of phone, and receive OTPs by email.', max_length=254, null=True, unique=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='handoffcode',
            name='rider_delivery',
            field=models.ForeignKey(blank=True, help_text="Which seller's delivery this code belongs to. Null for order-level stages (admin_to_officer, officer_to_customer).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handoff_codes', to='mall.riderdelivery'),
        ),
        migrations.CreateModel(
            name='RiderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(help_text='Primary phone (WhatsApp).', max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('tricycle', 'Tricycle (Pragya)'), ('foot', 'On Foot'), ('other', 'Other')], default='motorcycle', max_length=12)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(choices=[('greater_accra', 'Greater Accra Region'), ('ashanti', 'Ashanti Region'), ('western', 'Western Region'), ('western_north', 'Western North Region'), ('central', 'Central Region'), ('eastern', 'Eastern Region'), ('volta', 'Volta Region'), ('oti', 'Oti Region'), ('bono', 'Bono Region'), ('bono_east', 'Bono East Region'), ('ahafo', 'Ahafo Region'), ('northern', 'Northern Region'), ('savannah', 'Savannah Region'), ('north_east', 'North East Region'), ('upper_east', 'Upper East Region'), ('upper_west', 'Upper West Region')], default='greater_accra', help_text='Where the applicant mainly wants to ride.', max_length=50)),
                ('id_document', models.FileField(help_text="National ID, passport, or driver's license", upload_to='rider_applications/ids/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rider_applications/photos/')),
                ('notes', models.TextField(blank=True, help_text="Applicant's message — experience, availability, etc.")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decision_note', models.CharField(blank=True, default='', max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_rider', models.ForeignKey(blank=True, help_text='Set to the Rider record created when this application was approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='mall.rider')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_rider_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
