# Generated by Django 5.2.14 on 2026-09-18 02:10

import django.db.models.deletion
import mall.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0069_order_delivery_digital_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[mall.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', validators=[mall.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='uploadedproductimage',
            name='image',
            field=models.ImageField(upload_to='product_uploads/images/', validators=[mall.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[mall.validators.validate_image_size]),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label to remember what this key is for, e.g. "Acme Logistics integration".', max_length=100)),
                ('prefix', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('key_hash', models.CharField(editable=False, max_length=128)),
                ('scopes', models.CharField(help_text='Comma-separated scopes, e.g. catalog:read,orders:write', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
            },
        ),
    ]
