# Generated by Django 5.2.14 on 2026-09-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0070_alter_product_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Rider's base/home GPS latitude, for proximity-based dispatch.", null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Rider's base/home GPS longitude, for proximity-based dispatch.", null=True),
        ),
    ]
