# Generated by Django 5.2.14 on 2026-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0071_rider_gps_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('truck', 'Delivery Truck'), ('tricycle', 'Tricycle (Pragya)'), ('foot', 'On Foot'), ('other', 'Other')], default='motorcycle', max_length=12),
        ),
        migrations.AlterField(
            model_name='riderapplication',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('truck', 'Delivery Truck'), ('tricycle', 'Tricycle (Pragya)'), ('foot', 'On Foot'), ('other', 'Other')], default='motorcycle', max_length=12),
        ),
    ]
