# Generated by Django 5.2.14 on 2026-09-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0072_alter_rider_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderdelivery',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderdelivery',
            name='is_open_for_pickup',
            field=models.BooleanField(default=False, help_text='True when this delivery is open for any active rider in the region to claim.'),
        ),
        migrations.AddField(
            model_name='riderdelivery',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
